version: '3'

services:
  sopel:
    image: adamus1red/sopel:7.1.2
    container_name: sopel
    restart: always
    volumes:
      - ./sopel_config/default.cfg:/home/sopel/.sopel/default.cfg
      - ./sopel_modules/:/home/sopel/.sopel/modules/
